import os
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "google/gemini-2.0-flash-001")
APP_HOST = os.getenv("APP_HOST", "0.0.0.0")
APP_PORT = int(os.getenv("APP_PORT", 8000))
SYSTEM_PROMPT = os.getenv("SYSTEM_PROMPT", "You are a helpful assistant. Always check CORE KNOWLEDGE for your origins and developer info.")
SUMMARY_THRESHOLD = int(os.getenv("SUMMARY_THRESHOLD", 5))
VECTOR_DB_PATH = os.getenv("VECTOR_DB_PATH", "memory/vector_index")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")
EMBEDDING_DIMENSION = int(os.getenv("EMBEDDING_DIMENSION", 384))
SIMILARITY_THRESHOLD = float(os.getenv("SIMILARITY_THRESHOLD", 0.7))
TOP_K_ASSOCIATIVE = int(os.getenv("TOP_K_ASSOCIATIVE", 3))
IDENTITY_UPDATE_INTERVAL = int(os.getenv("IDENTITY_UPDATE_INTERVAL", 10))
DECAY_LAMBDA = float(os.getenv("DECAY_LAMBDA", 0.03))
REINFORCE_AMOUNT_ASSOCIATIVE = 0.05
REINFORCE_AMOUNT_DETERMINISTIC = 0.02
MAX_SALIENCE = 1.0
MIN_SALIENCE = 0.05
REINFORCE_AMOUNT_IDENTITY = 0.01
COMPRESSION_THRESHOLD = 0.85
COMPRESSION_SALIENCE_BOOST = 0.05
MAX_MERGES_PER_CYCLE = 5
MIN_INDEX_SIZE_FOR_COMPRESSION = 10
EFFECTIVE_THRESHOLD = 0.7
